name: MCBouncer
version: ${project.version}
author: MCBouncer Staff
website: http://mcbouncer.com/
main: com.mcbouncer.MCBouncerBukkit
description: MCBouncer is a cloud-based ban suite and protection program that is modular, unbiased, and fair to its users.
commands:
  ban:
    description: 'Ban a username'
    usage: '/<command> [reason]'
  timedban:
    description: 'Ban a username for a set time'
    usage: '/<command> <duration> [reason]'
    aliases: ['tban', 'tempban']
  unban:
    description: 'Unban a username'
    usage: '/<command> playername'
    aliases: ['delban', 'pardon']
  banip:
    description: 'Ban an IP'
    usage: '/<command> playername/IP'
  unbanip:
    description: 'Unban an IP'
    usage: '/<command> playername/IP'
  lookup:
    description: 'See all bans by a username'
    usage: '/<command> playername'
  kick:
    description: 'Kick a user from the server'
    usage: '/<command> playername [reason]'
    aliases: ['boot']
  mcbouncer:
    description: 'MCBouncer commands'
    usage: '/<command> [help|version|reload]'
    aliases: ['mcb']
  addnote:
    description: 'Adds a note'
    usage: '/<command> playername note'
  addglobalnote:
    description: 'Adds a global note'
    usage: '/<command> playername note'
    aliases: ['addgnote']
  removenote:
    description: 'Removes a note'
    usage: '/<command> noteid'
    aliases: ['delnote']
    
permissions:
  mcbouncer.admin:
    description: Allow a player all mcbouncer permissions
    children:
      mcbouncer.mod: true
      mcbouncer.reload: true
  mcbouncer.mod:
    description: Allow a player all mcbouncer permissions except mcbouncer.reload
    children:
      mcbouncer.command.ban: true
      mcbouncer.commnad.unban: true
      mcbouncer.command.banip: true
      mcbouncer.command.unbanip: true
      mcbouncer.command.lookup: true
      mcbouncer.command.kick: true
      mcbouncer.command.addnote: true
      mcbouncer.command.addnote.global: true
      mcbouncer.command.removenote: true
  mcbouncer.command.ban:
    description: Allow a player to ban using mcbouncer
  mcbouncer.command.unban:
    description: Allow a player to unban using mcbouncer
  mcbouncer.command.banip:
    description: Allow a player to ban ip using mcbouncer
  mcbouncer.command.unbanip:
    description: Allow a player to unban an ip using mcbouncer
  mcbouncer.command.lookup:
    description: Allow a player to do ban lookups using mcbouncer
  mcbouncer.command.kick:
    description: Allow a player to kick using mcbouncer
  mcbouncer.command.addnote:
    description: Allow a player to add notes using mcbouncer
  mcbouncer.command.addnote.global:
    description: Allow a player to add global notes using mcbouncer
  mcbouncer.command.removenote:
    description: Allow a player to remove notes using mcbouncer
  mcbouncer.command.reload:
    description: Allow a playing to reload the mcbouncer configuration
